version: 0.2
phases: 
  install:
    runtime-versions:
      php: '7.3'
    commands:
    - composer install
    
  build:
    commands:
      - php artisan config:cache
  post_build:
    commands: 
      #- php artisan test     
      - ./vendor/bin/phpunit
      - echo Build completed on `date`
      - echo $CODEBUILD_SRC_DIR
reports:
  test-report:
    files:
      - 'test-result.json'
    base-directory: 'tests'
    discard-paths: no
    file-format: "JUNITXML"