version: 0.2
phases: 
  install:
    runtime-versions:
      php: '7.3'
    commands:
    - composer install
    
  build:
    commands:
      - php artisan config:cache
  post_build:
    commands:      
      - ./vendor/bin/phpunit
reports:
  arn:aws:codebuild:ap-southeast-1:414584919839:report-group/lab-build-application-test-report:
    files:
      - "reports/php/reports.xml"
    file-format: "JUNITXML"