version: 0.2
phases: 
  install:
    runtime-versions:
      php: '7.3'
    commands:
    - composer install
  build:
    commands:
    - phpunit
reports:
  test-report:
    files:
      - build/reports.xml
    file-format: JunitXml